/**
 * Abstract Base Class for PixelIDE AI Providers
 * Every provider (Gemini, OpenAI, Claude, Groq, Ollama, etc.) must implement this interface.
 */

export class BaseAIProvider {
  constructor(name = "base-provider") {
    this.name = name;
  }

  /**
   * Generates content from prompt using the configured AI provider API.
   *
   * @param {Object} params
   * @param {string} params.prompt - High-level text prompt or code context
   * @param {string} [params.systemInstruction] - System persona or instructions
   * @param {Object} [params.config] - Overrides for temperature, model, maxTokens, apiKey
   * @param {AbortSignal} [params.signal] - AbortSignal for request cancellation
   * @returns {Promise<string>} Text output generated by provider
   */
  async generateContent({ prompt, systemInstruction, config, signal }) {
    throw new Error(
      `Provider ${this.name} must implement the generateContent({ prompt, systemInstruction, config, signal }) method.`
    );
  }

  /**
   * Validates provider credentials and configuration.
   * @param {Object} config
   * @returns {boolean}
   */
  validateConfig(config) {
    if (!config || !config.apiKey) {
      return false;
    }
    return true;
  }
}

export default BaseAIProvider;
